### ISSUE TITLE
online Guilds not work

### ISSUE THREAD

**Issue by Wellington9023** [UMNFuN/FUNGuild#38]
I got no results when I used the example OTU，showing _**0 assignments were made on OTUs within the input file!**_

**Comment by Hide-Fun** [comment]
I am experiencing the same problem too...

**Comment by ZeweiSong** [comment]
I think it is due to some format change on our side. I’ll check on this today and tomorrow, stay tune!

Zewei

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Hide-Fun** [comment]
Thanky you @ZeweiSong !!

By the way, does it matter what is mentioned "This past year I removed references to the online tool from the website as A) we are encouraging use of the script; and B) it has become difficult to support the online tool." at #31 by @UMNFuN?

**Comment by ZeweiSong** [comment]
I would try the script if you know what to do. I will only check the script too.

Cheers,

Zewei

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Hide-Fun** [comment]
OK thank you.

**Comment by Wellington9023** [comment]
thank you very much！


On 12/15/2020 16:31，Hidehito Okada<notifications@github.com> wrote：

OK thank you.

**Comment by ZeweiSong** [comment]
Hi, All

The **Guilds_v1.1** should work now for the new database. You have to clone or download the new script to use it.

    git clone https://github.com/UMNFuN/FUNGuild
    FUNGuild/Guilds_v1.1.py -otu your_otu_table.txt

**Comment by Wellington9023** [comment]
I use online app in this address http://www.stbates.org/guilds/app.php  it seems not working


On 12/15/2020 16:52，Zewei Song<notifications@github.com> wrote：

Hi, All

The Guilds_v1.1 should work now for the new database. You have to clone or download the new script to use it.

git clone https://github.com/UMNFuN/FUNGuild
FUNGuild/Guilds_v1.1.py -otu your_otu_table.txt

**Comment by ZeweiSong** [comment]
Try to use the script. The online portal is not fixed yet.

Zewei

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Wellington9023** [comment]
OK thank you ！


On 12/15/2020 17:01，Zewei Song<notifications@github.com> wrote：

Try to use the script. The online portal is not fixed yet.

Zewei

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ZeweiSong** [comment]
For beginner of script, the output should looks like this:

```
(base) zewei@SZ15366-02:/mnt/e/LabSpace/FUNGuild$ debug/FUNGuild/Guilds_v1.1.py -otu otu_table.txt
FunGuild v1.0 Beta
Connecting with FUNGuild database ...

Reading in the OTU table: 'otu_table.txt'

Searching the FUNGuild database...
10%
20%
30%
40%
50%
60%
70%
80%
90%
100%

Found 7 matching taxonomy records in the database.
Dereplicating and sorting the result...
FunGuild tried to assign function to 10 OTUs in 'otu_table.txt'.
FUNGuild made assignments on 5 OTUs.
Result saved to 'otu_table.guilds.txt'

Total calculating time: 7.53 seconds.
```

**Comment by Hide-Fun** [comment]
Thanks for the quick response @ZeweiSong !!

**Comment by Wellington9023** [comment]
thanks for your help I will try it！


On 12/15/2020 17:05，Zewei Song<notifications@github.com> wrote：

For beginner of script, the output should looks like this:

(base) zewei@SZ15366-02:/mnt/e/LabSpace/FUNGuild$ debug/FUNGuild/Guilds_v1.1.py -otu otu_table.txt
FunGuild v1.0 Beta
Connecting with FUNGuild database ...

Reading in the OTU table: 'otu_table.txt'

Searching the FUNGuild database...
10%
20%
30%
40%
50%
60%
70%
80%
90%
100%

Found 7 matching taxonomy records in the database.
Dereplicating and sorting the result...
FunGuild tried to assign function to 10 OTUs in 'otu_table.txt'.
FUNGuild made assignments on 5 OTUs.
Result saved to 'otu_table.guilds.txt'

Total calculating time: 7.53 seconds.

**Comment by ZeweiSong** [comment]
This is a comment from Scott:
>>16 Dec. 2020 - FUNGuild community: We have recently had to shift the FUNGuild database over to a new virtual server. While we were on track for a seamless transfer, we ran into complications that delayed the process. Our sincere apologies for any inconvenience that this may have caused. The following access points are now available for the updated FUNGuild database: http://www.stbates.org/funguild_db.php and http://www.stbates.org/funguild_db_2.php. Currently, there are issues with ca. 2000 names that we hope to have resolved by the weekend, thus fully restoring the FUNGuild database at that time. This update includes new features for functionality, which we hope will aid in improving the quality of the data overall. Additions and corrections can be sent directly to stbates@purdue.edu.<<

**Comment by Betula0422** [comment]
I got no results when I used the example OTU，showing 0 assignments were made on OTUs within the input file! This problem still exist.

**Comment by Betula0422** [comment]
I got no results when I used the example OTU，showing 0 assignments were made on OTUs within the input file! This problem still exists.

**Comment by ZeweiSong** [comment]
Hi, Betula

Can you post here what you did to get 0 assignments?

Thanks,

Zewei

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Betula0422** [comment]
> Hi, Betula Can you post here what you did to get 0 assignments? Thanks, Zewei Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
> […](#)
> ________________________________ From: Betula0422 <notifications@github.com> Sent: Wednesday, January 6, 2021 4:47:56 PM To: UMNFuN/FUNGuild <FUNGuild@noreply.github.com> Cc: Zewei Song <songzewei@outlook.com>; Mention <mention@noreply.github.com> Subject: Re: [UMNFuN/FUNGuild] online Guilds not work (#38) I got no results when I used the example OTU，showing 0 assignments were made on OTUs within the input file! This problem still exist. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUMNFuN%2FFUNGuild%2Fissues%2F38%23issuecomment-755168199&data=04%7C01%7C%7Caa857089e3324049954f08d8b21fc3ec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637455196786683408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=By5VtJ2fk0cDQWlyvk%2BvLpheFKJ%2FrFpH5iIC%2FbnfmyU%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB3EDW6JMAPWFDF5FH3PFHTSYQPTZANCNFSM4U2EQDSQ&data=04%7C01%7C%7Caa857089e3324049954f08d8b21fc3ec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637455196786683408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AgP5fbxqfrmVIfnv3PnI3YSVS7EPgXnt1r4%2Fk3%2B8364%3D&reserved=0>.

I selected the example otu table online: "http://www.stbates.org/guilds/app.php", and then clicked "Begin Analysis" , the Guilds v1.0 Beta reported that: "0 assignments were made on OTUs within the input file!" And I downloaded the output files, none of the OTUs had been assigned.

**Comment by ZeweiSong** [comment]
Try to use the script, remember to use Anaconda3 environment.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Betula0422** [comment]
> Try to use the script, remember to use Anaconda3 environment. 获取 Outlook for Android<https://aka.ms/ghei36>
> […](#)
> ________________________________ From: Betula0422 <notifications@github.com> Sent: Wednesday, January 6, 2021 6:31:14 PM To: UMNFuN/FUNGuild <FUNGuild@noreply.github.com> Cc: Zewei Song <songzewei@outlook.com>; Mention <mention@noreply.github.com> Subject: Re: [UMNFuN/FUNGuild] online Guilds not work (#38) Hi, Betula Can you post here what you did to get 0 assignments? Thanks, Zewei Sent from Mailhttps://go.microsoft.com/fwlink/?LinkId=550986<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D550986&data=04%7C01%7C%7C6f227803e62d43a71c9708d8b22e3247%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637455258765493722%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZiQe4pExL7rPcI1KOVHRbEn6gAo98uULROIUjL7pDxM%3D&reserved=0> for Windows 10 …
> ________________________________ From: Betula0422 notifications@github.com<mailto:notifications@github.com> Sent: Wednesday, January 6, 2021 4:47:56 PM To: UMNFuN/FUNGuild FUNGuild@noreply.github.com<mailto:FUNGuild@noreply.github.com> Cc: Zewei Song songzewei@outlook.com<mailto:songzewei@outlook.com>; Mention mention@noreply.github.com<mailto:mention@noreply.github.com> Subject: Re: [UMNFuN/FUNGuild] online Guilds not work (#38<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUMNFuN%2FFUNGuild%2Fissues%2F38&data=04%7C01%7C%7C6f227803e62d43a71c9708d8b22e3247%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637455258765493722%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2LpRoD9gfAhytOakM7bLhzyNIp%2BlHKGrlnw8eqstn1E%3D&reserved=0>) I got no results when I used the example OTU，showing 0 assignments were made on OTUs within the input file! This problem still exist. ― You are receiving this because you were mentioned. Reply to this email directly, view it on GitHubhttps://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUMNFuN%2FFUNGuild%2Fissues%2F38%23issuecomment-755168199&data=04%7C01%7C%7Caa857089e3324049954f08d8b21fc3ec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637455196786683408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=By5VtJ2fk0cDQWlyvk%2BvLpheFKJ%2FrFpH5iIC%2FbnfmyU%3D&reserved=0<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUMNFuN%2FFUNGuild%2Fissues%2F38%23issuecomment-755168199&data=04%7C01%7C%7C6f227803e62d43a71c9708d8b22e3247%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637455258765503672%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b%2Fbcd80Sl5J51AKCuWl7Bp1Tt4dzd75mr413CPMUPKk%3D&reserved=0>, or unsubscribehttps://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB3EDW6JMAPWFDF5FH3PFHTSYQPTZANCNFSM4U2EQDSQ&data=04%7C01%7C%7Caa857089e3324049954f08d8b21fc3ec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637455196786683408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AgP5fbxqfrmVIfnv3PnI3YSVS7EPgXnt1r4%2Fk3%2B8364%3D&reserved=0<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB3EDW6JMAPWFDF5FH3PFHTSYQPTZANCNFSM4U2EQDSQ&data=04%7C01%7C%7C6f227803e62d43a71c9708d8b22e3247%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637455258765503672%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FMpCSYvVqZCPCdieZmy0HvyXwTOFCiM1zi%2BRfus1AlM%3D&reserved=0>. I selected the example otu table online: "http://www.stbates.org/guilds/app.php<https://apac01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.stbates.org%2Fguilds%2Fapp.php&data=04%7C01%7C%7C6f227803e62d43a71c9708d8b22e3247%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637455258765513625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KmgHeI0ZZdoO8oG%2Bo%2F%2BmCEjF%2FkZ1lUCjBWcEVKPMl%2Bc%3D&reserved=0>", and then clicked "Begin Analysis" , the Guilds v1.0 Beta reported that: "0 assignments were made on OTUs within the input file!" And I downloaded the output files, none of the OTUs had been assigned. ― You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUMNFuN%2FFUNGuild%2Fissues%2F38%23issuecomment-755219551&data=04%7C01%7C%7C6f227803e62d43a71c9708d8b22e3247%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637455258765513625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8nCP7fvAvh8QeINHHg4EZs%2B4i%2Fp9r8mbbOxGIylP5x4%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB3EDW4ZS3HCEDQLOJNFGRLSYQ3XFANCNFSM4U2EQDSQ&data=04%7C01%7C%7C6f227803e62d43a71c9708d8b22e3247%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637455258765523582%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vMn6%2FbZvFnnZs2ZnZSyzbTC7sw7nhpB26hEDL4DyqqI%3D&reserved=0>.

Thanks for your reply! I'll try it!
